spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl
    username: rm560077
    password: 300903
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cache:
    type: simple

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.orbitbook.booking: DEBUG
    org.springframework.cloud.openfeign: DEBUG
